name: Generate Clinic Markdown

on:
  push:
    paths:
      - 'clinics/**.json'   # Trigger when JSON files change
      - '.github/workflows/generate_clinic_md.yml'
  workflow_dispatch:     # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run the markdown generator
        run: |
          pip install -r requirements.txt || true
          python automation/generate_clinic_md.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add markdown/clinics/*.md
          git commit -m "Auto-generate clinic markdown from JSON" || echo "No changes to commit"
          git push
